#!/usr/bin/env python3
"""Replace common Chinese UI text and dev comments with English across Frontend/src."""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src"
EXTENSIONS = {".vue", ".js", ".scss", ".html"}

# Longest phrases first to avoid partial replacements
REPLACEMENTS = [
    ("恢复默认的生成基础路径", "Restore default generation base path"),
    ("默认为zip压缩包下载，也可以自定义生成路径", "Default is ZIP download; you can also set a custom output path"),
    ("填写磁盘绝对路径，若不填写，则生成到当前Web项目下", "Absolute disk path; if empty, generates under the current web project"),
    ("分配到指定菜单下，例如 系统管理", "Assign under a menu, e.g. System Management"),
    ("树节点的显示名称字段名， 如：dept_name", "Tree node display name field, e.g. dept_name"),
    ("树显示的父编码字段名， 如：parent_Id", "Tree parent code field, e.g. parent_Id"),
    ("树显示的编码字段名， 如：dept_id", "Tree code field, e.g. dept_id"),
    ("关联子表的表名， 如：sys_user", "Related child table name, e.g. sys_user"),
    ("子表关联的外键名， 如：user_id", "Child table foreign key, e.g. user_id"),
    ("用作类描述，例如 用户", "Class description, e.g. User"),
    ("请选择要导入的表", "Please select tables to import"),
    ("确定要Clear所有组件吗？", "Clear all components?"),
    ("生成类型不能为空", "Generation type is required"),
    ("请选择生成模板", "Please select a generation template"),
    ("请输入Package Path", "Please enter package path"),
    ("请输入Module Name", "Please enter module name"),
    ("请输入Business Name", "Please enter business name"),
    ("请输入Function Name", "Please enter function name"),
    ("手机号格式错误", "Invalid phone number format"),
    ("请输入选项名", "Please enter option label"),
    ("请输入选项值", "Please enter option value"),
    ("请输入文件名", "Please enter file name"),
    ("地图服务已切换至 Mapbox GL JS", "Map service switched to Mapbox GL JS"),
    ("设备 Mapbox 地图初始化完成", "Device Mapbox map initialized"),
    ("设备地图点击事件", "Device map click event"),
    ("标记拖拽结束事件", "Marker drag end event"),
    ("搜索地址时出错:", "Error searching address:"),
    ("地图弹窗已关闭，所有状态已重置", "Map dialog closed; state reset"),
    ("解析意图失败:", "Failed to parse intent:"),
    ("获取到的数据:", "Fetched data:"),
    ("最终提示词:", "Final prompt:"),
    ("获取数据失败:", "Failed to fetch data:"),
    ("获取告警数据失败:", "Failed to fetch alarm data:"),
    ("获取设备数据失败:", "Failed to fetch device data:"),
    ("获取服务器数据失败:", "Failed to fetch server data:"),
    ("获取今日数据失败:", "Failed to fetch today's data:"),
    ("获取轨迹详情失败:", "Failed to fetch track details:"),
    ("获取记录列表失败", "Failed to fetch record list"),
    ("解析strRes数据失败:", "Failed to parse strRes data:"),
    ("计算交流时长失败:", "Failed to calculate interaction duration:"),
    ("导出PDF失败", "Failed to export PDF"),
    ("位置变化，推荐使用", "Location changed; recommended"),
    ("切换到", "Switched to"),
    ("初始化Google地图", "Initializing Google Map"),
    ("mqtt.opens状态变更为:", "mqtt.opens status changed to:"),
    ("网络不可用，使用本地安装包", "Network unavailable; using local installer"),
    ("WebSocket连接成功，准备恢复配置", "WebSocket connected; restoring configuration"),
    ("操作失败", "Operation failed"),
    ("已保存监控配置:", "Saved monitoring configuration:"),
    ("分屏数量:", "Split screen count:"),
    ("playing device数量:", "Playing device count:"),
    ("保存时间:", "Saved at:"),
    ("保存配置失败:", "Failed to save configuration:"),
    ("开始恢复监控配置:", "Restoring monitoring configuration:"),
    ("保存时间:", "Saved at:"),
    ("恢复分屏数量:", "Restored split screen count:"),
    ("无效的分屏数量:", "Invalid split screen count:"),
    ("恢复统计:", "Restore statistics:"),
    ("总设备数:", "Total devices:"),
    ("成功恢复:", "Restored successfully:"),
    ("恢复配置失败:", "Failed to restore configuration:"),
    ("来自组件", "From component"),
    ("改变了", "changed"),
    ("底部图片", "Bottom image"),
    ("值改变", "Value changed"),
    ("没有灵敏度", "No sensitivity"),
    ("画点", "Draw point"),
    ("画线", "Draw line"),
    ("双击编辑", "double-click to edit"),
    ("个人中心", "Profile"),
    ("分配角色", "Assign Roles"),
    ("分配用户", "Assign Users"),
    ("字典数据", "Dictionary Data"),
    ("调度日志", "Job Log"),
    ("修改生成配置", "Edit Generator Config"),
    ("导入表", "Import Table"),
    ("更新时间", "Updated At"),
    ("安装位置", "Installation Location"),
    ("进出类型", "Entry/Exit Type"),
    ("门禁序号", "Access Control Index"),
    ("zip压缩包", "ZIP archive"),
    ("自定义路径", "Custom path"),
    ("其他信息", "Other Info"),
    ("关联信息", "Relation Info"),
    ("请选择系统菜单", "Please select system menu"),
    ("请选择要导入的表", "Please select tables to import"),
    ("单机", "Standalone"),
    ("集群", "Cluster"),
    ("组件属性", "Component Props"),
    ("表单属性", "Form Props"),
    ("查看组件文档", "View component docs"),
    ("组件类型", "Component Type"),
    ("请选择组件类型", "Please select component type"),
    ("字段名", "Field Name"),
    ("请输入字段名（v-model）", "Enter field name (v-model)"),
    ("组件名", "Component Name"),
    ("标题", "Title"),
    ("请输入标题", "Please enter title"),
    ("占位提示", "Placeholder"),
    ("请输入占位提示", "Please enter placeholder"),
    ("开始占位", "Start Placeholder"),
    ("结束占位", "End Placeholder"),
    ("表单栅格", "Form Grid Span"),
    ("栅格间隔", "Gutter"),
    ("布局模式", "Layout Mode"),
    ("水平排列", "Horizontal Align"),
    ("请选择水平排列", "Please select horizontal align"),
    ("垂直排列", "Vertical Align"),
    ("标签宽度", "Label Width"),
    ("请输入标签宽度", "Please enter label width"),
    ("组件宽度", "Component Width"),
    ("请输入组件宽度", "Please enter component width"),
    ("默认值", "Default Value"),
    ("请输入默认值", "Please enter default value"),
    ("至少应选", "Min Selected"),
    ("最多可选", "Max Selected"),
    ("前缀", "Prefix"),
    ("请输入前缀", "Please enter prefix"),
    ("后缀", "Suffix"),
    ("请输入后缀", "Please enter suffix"),
    ("前图标", "Prefix Icon"),
    ("请输入前图标名称", "Please enter prefix icon name"),
    ("后图标", "Suffix Icon"),
    ("请输入后图标名称", "Please enter suffix icon name"),
    ("选项分隔符", "Option Separator"),
    ("请输入选项分隔符", "Please enter option separator"),
    ("最小行数", "Min Rows"),
    ("最大行数", "Max Rows"),
    ("最小值", "Min Value"),
    ("最大值", "Max Value"),
    ("步长", "Step"),
    ("步数", "Step count"),
    ("精度", "Precision"),
    ("按钮位置", "Button Position"),
    ("最多输入", "Max Length"),
    ("请输入字符长度", "Please enter max length"),
    ("开启提示", "Active Text"),
    ("请输入开启提示", "Please enter active text"),
    ("关闭提示", "Inactive Text"),
    ("请输入关闭提示", "Please enter inactive text"),
    ("开启值", "Active Value"),
    ("请输入开启值", "Please enter active value"),
    ("关闭值", "Inactive Value"),
    ("请输入关闭值", "Please enter inactive value"),
    ("时间类型", "Time Type"),
    ("请选择时间类型", "Please select time type"),
    ("文件字段名", "File Field Name"),
    ("请输入上传文件字段名", "Please enter upload field name"),
    ("文件类型", "File Type"),
    ("请选择文件类型", "Please select file type"),
    ("图片", "Image"),
    ("视频", "Video"),
    ("音频", "Audio"),
    ("文件大小", "File Size"),
    ("请输入文件大小", "Please enter file size"),
    ("上传地址", "Upload URL"),
    ("请输入上传地址", "Please enter upload URL"),
    ("列表类型", "List Type"),
    ("按钮文字", "Button Text"),
    ("请输入按钮文字", "Please enter button text"),
    ("分隔符", "Separator"),
    ("请输入分隔符", "Please enter separator"),
    ("时间段", "Time Range"),
    ("请输入时间段", "Please enter time range"),
    ("时间格式", "Time Format"),
    ("请输入时间格式", "Please enter time format"),
    ("选项名", "Option Label"),
    ("选项值", "Option Value"),
    ("数据类型", "Data Type"),
    ("标签键名", "Label Key"),
    ("请输入标签键名", "Please enter label key"),
    ("值键名", "Value Key"),
    ("请输入值键名", "Please enter value key"),
    ("子级键名", "Children Key"),
    ("请输入子级键名", "Please enter children key"),
    ("选项样式", "Option Style"),
    ("开启颜色", "Active Color"),
    ("关闭颜色", "Inactive Color"),
    ("允许半选", "Allow Half"),
    ("辅助文字", "Show Text"),
    ("显示分数", "Show Score"),
    ("显示间断点", "Show Stops"),
    ("范围选择", "Range"),
    ("是否带边框", "Border"),
    ("颜色格式", "Color Format"),
    ("请选择颜色格式", "Please select color format"),
    ("选项尺寸", "Option Size"),
    ("输入统计", "Show Word Limit"),
    ("严格步数", "Step Strictly"),
    ("是否多选", "Multiple"),
    ("展示全路径", "Show All Levels"),
    ("可否筛选", "Filterable"),
    ("能否清空", "Clearable"),
    ("显示提示", "Show Tip"),
    ("多选文件", "Multiple Files"),
    ("自动上传", "Auto Upload"),
    ("是否只读", "Readonly"),
    ("是否禁用", "Disabled"),
    ("是否可搜索", "Filterable"),
    ("是否必填", "Required"),
    ("表达式", "Pattern"),
    ("请输入正则", "Please enter regex"),
    ("错误提示", "Error Message"),
    ("请输入错误提示", "Please enter error message"),
    ("表单名", "Form Ref"),
    ("请输入表单名（ref）", "Please enter form ref"),
    ("表单模型", "Form Model"),
    ("请输入数据模型", "Please enter form model"),
    ("校验模型", "Rules Model"),
    ("请输入校验模型", "Please enter rules model"),
    ("表单尺寸", "Form Size"),
    ("标签对齐", "Label Align"),
    ("布局结构树", "Layout Tree"),
    ("正则校验", "Regex Rules"),
    ("基本信息", "Basic Info"),
    ("字段信息", "Column Info"),
    ("生成信息", "Generator Info"),
    ("字段列名", "Column Name"),
    ("字段描述", "Column Comment"),
    ("物理类型", "Column Type"),
    ("java属性", "Java Field"),
    ("查询方式", "Query Type"),
    ("显示类型", "HTML Type"),
    ("字典类型", "Dict Type"),
    ("请选择", "Please select"),
    ("文本框", "Input"),
    ("文本域", "Textarea"),
    ("下拉框", "Select"),
    ("单选框", "Radio"),
    ("复选框", "Checkbox"),
    ("日期控件", "DateTime"),
    ("图片上传", "Image Upload"),
    ("文件上传", "File Upload"),
    ("富文本控件", "Editor"),
    ("生成类型", "Output Type"),
    ("文件名", "File Name"),
    ("复制", "Copy"),
    ("重启", "Restart"),
    ("搜索", "Search"),
    ("重置", "Reset"),
    ("删除", "Delete"),
    ("修改", "Edit"),
    ("生成", "Generate"),
    ("预览", "Preview"),
    ("编辑", "Edit"),
    ("同步", "Sync"),
    ("提交", "Submit"),
    ("返回", "Back"),
    ("确 定", "Confirm"),
    ("取 消", "Cancel"),
    ("选项", "Options"),
    ("序号", "No."),
    ("插入", "Insert"),
    ("列表", "List"),
    ("查询", "Query"),
    ("必填", "Required"),
    ("查询字典数据列表", "Query dictionary data list"),
    ("查询字典数据详细", "Query dictionary data detail"),
    ("根据字典类型查询字典数据信息", "Query dictionary data by type"),
    ("新增字典数据", "Add dictionary data"),
    ("修改字典数据", "Update dictionary data"),
    ("删除字典数据", "Delete dictionary data"),
    ("查询字典类型列表", "Query dictionary type list"),
    ("查询字典类型详细", "Query dictionary type detail"),
    ("新增字典类型", "Add dictionary type"),
    ("修改字典类型", "Update dictionary type"),
    ("删除字典类型", "Delete dictionary type"),
    ("刷新字典缓存", "Refresh dictionary cache"),
    ("获取字典选择框列表", "Get dictionary option list"),
    ("查询设备信息列表", "Query device list"),
    ("查询设备信息详细", "Query device detail"),
    ("新增设备信息", "Add device"),
    ("修改设备信息", "Update device"),
    ("删除设备信息", "Delete device"),
    ("查询告警记录信息列表", "Query alarm record list"),
    ("查询告警记录信息详细", "Query alarm record detail"),
    ("新增告警记录信息", "Add alarm record"),
    ("修改告警记录信息", "Update alarm record"),
    ("删除告警记录信息", "Delete alarm record"),
    ("获取系统语言", "Get system locale"),
    ("设置系统语言", "Set system locale"),
    ("获取java系统配置信息", "Get Java system config"),
    ("音频状态总开关 10 开 20 关 status", "Audio master switch: 10 on, 20 off"),
    ("是否显示重新登录", "Whether to show re-login prompt"),
    ("创建axios实例", "Create axios instance"),
    ("axios中请求配置有baseURL选项，表示请求URL公共部分", "axios baseURL is the API URL prefix"),
    ("超时1000=1秒", "timeout in ms (1000 = 1 second)"),
    ("是否需要设置 token", "Whether to attach token"),
    ("是否需要防止数据重复提交", "Whether to prevent duplicate submit"),
    ("让每个请求携带自定义token 请根据实际情况自行修改", "Attach Bearer token to each request"),
    ("get请求映射params参数", "Serialize GET query params into URL"),
    ("请求地址", "Request URL"),
    ("请求数据", "Request data"),
    ("请求时间", "Request time"),
    ("间隔时间(ms)，小于此时间视为重复提交", "Interval (ms); shorter requests are treated as duplicates"),
    ("未设置状态码则默认成功状态", "Default to success when status code is missing"),
    ("获取错误信息", "Resolve error message"),
    ("二进制数据则直接返回", "Return binary payload as-is"),
    ("通用下载方法", "Common download helper"),
    ("侧边栏主题 深色主题theme-dark，浅色主题theme-light", "Sidebar theme: theme-dark or theme-light"),
    ("是否系统布局配置", "Whether to show layout settings"),
    ("是否显示顶部导航", "Whether to show top navigation"),
    ("是否显示 tagsView", "Whether to show tags view"),
    ("是否固定头部", "Whether to fix header"),
    ("是否显示logo", "Whether to show logo"),
    ("是否显示动态标题", "Whether to show dynamic title"),
    ("加载地图类型配置，值类型为 amap（高德地图）", "Map provider type (e.g. amap)"),
    ("地图默认中心坐标 [经度, 纬度]", "Default map center [lng, lat]"),
    ("版本类型", "Edition type"),
    ("沙特版（设备区域使用字典下拉）", "Saudi edition (device area uses dictionary select)"),
    ("标准版（设备区域使用部门树形选择器）", "Standard edition (device area uses department tree)"),
    ("字典管理页面", "Dictionary management page"),
    ("字典详情页面", "Dictionary detail page"),
    ("设备区域管理页面", "Device area management page"),
    ("设备区域页面", "Device area page"),
    ("设置语言 选项 en | zh", "Locale options: en | zh"),
    ("设置文本内容", "Message bundles"),
    ("非 vue 文件中使用这个方法", "Use this helper outside Vue SFCs"),
    ("使用i18n的 te 方法来检查是否能够匹配到对应键值", "Use i18n te() to check if key exists"),
    ("顶部区域", "Card header"),
    ("信息行", "Info rows"),
    ("操作按钮", "Actions"),
    ("标准版：设备区域树形选择器", "Standard edition: device area tree selector"),
    ("标准版：树形选择器", "Standard edition: tree selector"),
    ("沙特版：字典下拉", "Saudi edition: dictionary select"),
    ("粒子背景", "Particle background"),
    ("头部居中Logo", "Centered header logo"),
    ("主内容区域 - 表单居中", "Main content - centered form"),
    ("表单头部", "Form header"),
    ("表单", "Form"),
    ("底部版权", "Footer copyright"),
    ("整页左右分栏", "Full-page split layout"),
    ("粒子背景Canvas", "Particle background canvas"),
    ("头部Logo区域", "Header logo section"),
    ("主内容区域", "Main content"),
    ("登录卡片", "Login card"),
    ("校验失败 — 红色边框 + 粉色背景", "Validation error — red border and pink background"),
    ("标签", "Label"),
    ("输入框", "Input"),
    ("验证码", "Captcha"),
    ("登录选项行", "Login options row"),
    ("登录按钮", "Login button"),
    ("初始化粒子系统", "Initialize particle system"),
    ("鼠标移动事件", "Mouse move handler"),
    ("处理窗口大小变化", "Handle window resize"),
    ("创建粒子", "Create particles"),
    ("动画循环", "Animation loop"),
    ("更新和绘制粒子", "Update and draw particles"),
    ("粒子移动", "Move particles"),
    ("边界检测", "Boundary check"),
    ("鼠标交互", "Mouse interaction"),
    ("绘制粒子", "Draw particles"),
    ("绘制连线", "Draw connections"),
    ("销毁", "Destroy"),
    ("设置语言", "Set locale"),
    ("获取系统语言", "Get system locale"),
]

COMMENT_PATTERNS = [
    (r"//\s*单选按钮值变化时", "// When radio value changes"),
    (r"//\s*周期两个值变化时", "// When cycle range changes"),
    (r"//\s*平均两个值变化时", "// When average range changes"),
    (r"//\s*最近工作日值变化时", "// When nearest weekday changes"),
    (r"//\s*checkbox值变化时", "// When checkbox selection changes"),
    (r"//\s*计算两个周期值", "// Compute cycle range"),
    (r"//\s*计算平均用到的值", "// Compute average values"),
    (r"//\s*计算工作日格式", "// Format weekday rule"),
    (r"//\s*计算勾选的checkbox值合集", "// Compute selected checkbox values"),
    (r"//\s*仅获取当前年份", "// Use current year only"),
    (r"//\s*遮罩层", "// Loading state"),
    (r"//\s*选中数组", "// Selected ids"),
    (r"//\s*非单个禁用", "// Disable single-action"),
    (r"//\s*非多个禁用", "// Disable batch-action"),
    (r"//\s*显示搜索条件", "// Show search form"),
    (r"//\s*总条数", "// Total count"),
    (r"//\s*弹出层标题", "// Dialog title"),
    (r"//\s*是否显示弹出层", "// Dialog visible"),
    (r"//\s*查询参数", "// Query params"),
    (r"//\s*表单参数", "// Form data"),
    (r"//\s*表单校验", "// Form rules"),
    (r"//\s*取消按钮", "// Cancel"),
    (r"//\s*表单重置", "// Reset form"),
    (r"//\s*多选框选中数据", "// Selection change"),
]

CHINESE_RE = re.compile(r"[\u4e00-\u9fff]")


def process_file(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    original = text
    for zh, en in REPLACEMENTS:
        text = text.replace(zh, en)
    for pattern, repl in COMMENT_PATTERNS:
        text = re.sub(pattern, repl, text)
    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


def main():
    changed = []
    for path in ROOT.rglob("*"):
        if path.suffix not in EXTENSIONS:
            continue
        if process_file(path):
            changed.append(path.relative_to(ROOT.parent))
    remaining = []
    for path in ROOT.rglob("*"):
        if path.suffix not in EXTENSIONS:
            continue
        for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if CHINESE_RE.search(line) and "zh.js" not in str(path):
                remaining.append(f"{path.relative_to(ROOT.parent)}:{i}: {line.strip()[:120]}")
    print(f"Updated {len(changed)} files")
    if remaining:
        print(f"\nRemaining lines with Chinese ({len(remaining)}):")
        for line in remaining[:80]:
            print(line)
        if len(remaining) > 80:
            print(f"... and {len(remaining) - 80} more")


if __name__ == "__main__":
    main()
